### ISSUE TITLE
Basic setup

### ISSUE THREAD

**Issue by adjavaherian** [bitcraze/crazyflie-vision#1]
Are there any instructions on how to use this with a basic webcam?

**Comment by ataffanel** [comment]
This repos only contains the control and infrastructure part not the vision part (which is a bit misleading regarding the repos name I admit). The architecture is described in the wiki: https://wiki.bitcraze.io/doc:crazyflie:vision:setup.

Basically it all communicates with ZMQ and you need to provide a detector that transmit the X/Y/Z position of the Crazyflie to the controller.

We have created and pushed two such detector:
- A Kinnect based one that runs on Windows: https://github.com/bitcraze/kinect-detector-windows
- An AR based one, tested on Linux, with a simple webcam: https://github.com/bitcraze/crazyflie-ar-detector. The readme of this repos contains some info on how to get started.

**Comment by adjavaherian** [comment]
Gotcha.  Thanks.
